language: c
install:
  - |-
    path="$(pwd)"; cd;
    wget https://github.com/rednex/rgbds/archive/v0.3.3.tar.gz -O rgbds.tar.gz &&
    tar xf rgbds.tar.gz &&
    cd rgbds-0.3.3 &&
    sudo make install &&
    cd - &&
    rm -rf rgbds &&
    cd "$path" &&
    wget https://tilde.town/~minerobber/tetris/baserom.gb
script:
  - make
  - make verify
